### PR TITLE
Fixes #48

### LINKED ISSUE #48: Ctrl-clicking a map cell works incorrectly
Ctrl-clicking a map cell should display a window with info about this cell. Currently it does display the window **and** sends the hero to that location.

### PR DESCRIPTION
**Pull request by watabou**
Besides actually fixing the issue, it also adds displaying the setting window as a secondary action to the menu button (i.e. ctrl-clicking the menu button calls that windows)

### CODE REVIEW

File: PD-classes/src/com/watabou/noosa/ui/Button.java [hunk 1]
```diff
@@ -52,7 +52,11 @@ protected void onTouchUp(NoosaInputProcessor.Touch touch) {
 			@Override
 			protected void onClick( NoosaInputProcessor.Touch touch ) {
 				if (!processed) {
-					Button.this.onClick();
+					if (NoosaInputProcessor.modifier && onLongClick()) {
+					// ...
```
Comment (Arcnor) [inline PD-classes/src/com/watabou/noosa/ui/Button.java]: Are we missing something here? If we are not, maybe it will be wise to add something like "Do nothing" instead of "..." ?

Comment (watabou) [inline PD-classes/src/com/watabou/noosa/ui/Button.java]: Yes, maybe. It's just an artifact of my code style :)
